server:
  port: 8000
spring:
  application:
    name: sr-back
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sr-back?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: aoyu
  devtools:
    restart:
      enabled: true
  mail:
    host: smtp.qq.com
    port: 587
    username: 339983216@qq.com
    password: whelhgjpovhqcadc
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-xxxxxxxx
      chat:
        options:
          model: qwen-turbo
          temperature: 0.7
  servlet:
    multipart:
      max-file-size: 500MB       
      max-request-size: 1000MB   

mybatis-plus:
  mapper-locations: classpath*:com/recipe/srback/mapper/xml/*.xml
  type-aliases-package: com.recipe.srback.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
knife4j:
  enable: true
springdoc:
  api-docs:
    enabled: true  
  swagger-ui:
    enabled: true  
jwt:
  secret: smartrepicebacksystem
  expiration: 7d
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug

aliyun:
  oss:
    enabled: false  # 暂时禁用OSS，需要时改为true并配置下面的信息
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: sr-back

user:
  default:
    nickname-prefix: user  # 默认昵称前缀
    avatar: https://smart-recipe.oss-cn-beijing.aliyuncs.com/default-avatar.jfif  # 默认头像